import turtle
t=turtle.Turtle()
t.begin_fill()
t.fillcolor("yellow")
t.setheading(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.end_fill()
turtle.done()